// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lenet5_Convolution2d_float_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_data_address0,
        out_data_ce0,
        out_data_we0,
        out_data_d0,
        out_data_q0,
        m_axi_data_AWVALID,
        m_axi_data_AWREADY,
        m_axi_data_AWADDR,
        m_axi_data_AWID,
        m_axi_data_AWLEN,
        m_axi_data_AWSIZE,
        m_axi_data_AWBURST,
        m_axi_data_AWLOCK,
        m_axi_data_AWCACHE,
        m_axi_data_AWPROT,
        m_axi_data_AWQOS,
        m_axi_data_AWREGION,
        m_axi_data_AWUSER,
        m_axi_data_WVALID,
        m_axi_data_WREADY,
        m_axi_data_WDATA,
        m_axi_data_WSTRB,
        m_axi_data_WLAST,
        m_axi_data_WID,
        m_axi_data_WUSER,
        m_axi_data_ARVALID,
        m_axi_data_ARREADY,
        m_axi_data_ARADDR,
        m_axi_data_ARID,
        m_axi_data_ARLEN,
        m_axi_data_ARSIZE,
        m_axi_data_ARBURST,
        m_axi_data_ARLOCK,
        m_axi_data_ARCACHE,
        m_axi_data_ARPROT,
        m_axi_data_ARQOS,
        m_axi_data_ARREGION,
        m_axi_data_ARUSER,
        m_axi_data_RVALID,
        m_axi_data_RREADY,
        m_axi_data_RDATA,
        m_axi_data_RLAST,
        m_axi_data_RID,
        m_axi_data_RFIFONUM,
        m_axi_data_RUSER,
        m_axi_data_RRESP,
        m_axi_data_BVALID,
        m_axi_data_BREADY,
        m_axi_data_BRESP,
        m_axi_data_BID,
        m_axi_data_BUSER,
        in_data,
        grp_fu_236_p_din0,
        grp_fu_236_p_din1,
        grp_fu_236_p_opcode,
        grp_fu_236_p_dout0,
        grp_fu_236_p_ce,
        grp_fu_240_p_din0,
        grp_fu_240_p_din1,
        grp_fu_240_p_opcode,
        grp_fu_240_p_dout0,
        grp_fu_240_p_ce,
        grp_fu_244_p_din0,
        grp_fu_244_p_din1,
        grp_fu_244_p_dout0,
        grp_fu_244_p_ce
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] out_data_address0;
output   out_data_ce0;
output   out_data_we0;
output  [31:0] out_data_d0;
input  [31:0] out_data_q0;
output   m_axi_data_AWVALID;
input   m_axi_data_AWREADY;
output  [31:0] m_axi_data_AWADDR;
output  [0:0] m_axi_data_AWID;
output  [31:0] m_axi_data_AWLEN;
output  [2:0] m_axi_data_AWSIZE;
output  [1:0] m_axi_data_AWBURST;
output  [1:0] m_axi_data_AWLOCK;
output  [3:0] m_axi_data_AWCACHE;
output  [2:0] m_axi_data_AWPROT;
output  [3:0] m_axi_data_AWQOS;
output  [3:0] m_axi_data_AWREGION;
output  [0:0] m_axi_data_AWUSER;
output   m_axi_data_WVALID;
input   m_axi_data_WREADY;
output  [31:0] m_axi_data_WDATA;
output  [3:0] m_axi_data_WSTRB;
output   m_axi_data_WLAST;
output  [0:0] m_axi_data_WID;
output  [0:0] m_axi_data_WUSER;
output   m_axi_data_ARVALID;
input   m_axi_data_ARREADY;
output  [31:0] m_axi_data_ARADDR;
output  [0:0] m_axi_data_ARID;
output  [31:0] m_axi_data_ARLEN;
output  [2:0] m_axi_data_ARSIZE;
output  [1:0] m_axi_data_ARBURST;
output  [1:0] m_axi_data_ARLOCK;
output  [3:0] m_axi_data_ARCACHE;
output  [2:0] m_axi_data_ARPROT;
output  [3:0] m_axi_data_ARQOS;
output  [3:0] m_axi_data_ARREGION;
output  [0:0] m_axi_data_ARUSER;
input   m_axi_data_RVALID;
output   m_axi_data_RREADY;
input  [31:0] m_axi_data_RDATA;
input   m_axi_data_RLAST;
input  [0:0] m_axi_data_RID;
input  [8:0] m_axi_data_RFIFONUM;
input  [0:0] m_axi_data_RUSER;
input  [1:0] m_axi_data_RRESP;
input   m_axi_data_BVALID;
output   m_axi_data_BREADY;
input  [1:0] m_axi_data_BRESP;
input  [0:0] m_axi_data_BID;
input  [0:0] m_axi_data_BUSER;
input  [31:0] in_data;
output  [31:0] grp_fu_236_p_din0;
output  [31:0] grp_fu_236_p_din1;
output  [1:0] grp_fu_236_p_opcode;
input  [31:0] grp_fu_236_p_dout0;
output   grp_fu_236_p_ce;
output  [31:0] grp_fu_240_p_din0;
output  [31:0] grp_fu_240_p_din1;
output  [1:0] grp_fu_240_p_opcode;
input  [31:0] grp_fu_240_p_dout0;
output   grp_fu_240_p_ce;
output  [31:0] grp_fu_244_p_din0;
output  [31:0] grp_fu_244_p_din1;
input  [31:0] grp_fu_244_p_dout0;
output   grp_fu_244_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[12:0] out_data_address0;
reg out_data_ce0;
reg out_data_we0;
reg[31:0] out_data_d0;
reg m_axi_data_ARVALID;
reg m_axi_data_RREADY;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] conv1_bias_address0;
reg    conv1_bias_ce0;
wire   [31:0] conv1_bias_q0;
wire   [7:0] conv1_weight_address0;
reg    conv1_weight_ce0;
wire   [31:0] conv1_weight_q0;
wire   [7:0] conv1_weight_address1;
reg    conv1_weight_ce1;
wire   [31:0] conv1_weight_q1;
wire   [7:0] conv1_weight_address2;
reg    conv1_weight_ce2;
wire   [31:0] conv1_weight_q2;
wire   [7:0] conv1_weight_address3;
reg    conv1_weight_ce3;
wire   [31:0] conv1_weight_q3;
wire   [7:0] conv1_weight_address4;
reg    conv1_weight_ce4;
wire   [31:0] conv1_weight_q4;
wire   [7:0] conv1_weight_address5;
reg    conv1_weight_ce5;
wire   [31:0] conv1_weight_q5;
wire   [7:0] conv1_weight_address6;
reg    conv1_weight_ce6;
wire   [31:0] conv1_weight_q6;
wire   [7:0] conv1_weight_address7;
reg    conv1_weight_ce7;
wire   [31:0] conv1_weight_q7;
wire   [7:0] conv1_weight_address8;
reg    conv1_weight_ce8;
wire   [31:0] conv1_weight_q8;
wire   [7:0] conv1_weight_address9;
reg    conv1_weight_ce9;
wire   [31:0] conv1_weight_q9;
wire   [7:0] conv1_weight_address10;
reg    conv1_weight_ce10;
wire   [31:0] conv1_weight_q10;
wire   [7:0] conv1_weight_address11;
reg    conv1_weight_ce11;
wire   [31:0] conv1_weight_q11;
wire   [7:0] conv1_weight_address12;
reg    conv1_weight_ce12;
wire   [31:0] conv1_weight_q12;
wire   [7:0] conv1_weight_address13;
reg    conv1_weight_ce13;
wire   [31:0] conv1_weight_q13;
wire   [7:0] conv1_weight_address14;
reg    conv1_weight_ce14;
wire   [31:0] conv1_weight_q14;
wire   [7:0] conv1_weight_address15;
reg    conv1_weight_ce15;
wire   [31:0] conv1_weight_q15;
wire   [7:0] conv1_weight_address16;
reg    conv1_weight_ce16;
wire   [31:0] conv1_weight_q16;
wire   [7:0] conv1_weight_address17;
reg    conv1_weight_ce17;
wire   [31:0] conv1_weight_q17;
wire   [7:0] conv1_weight_address18;
reg    conv1_weight_ce18;
wire   [31:0] conv1_weight_q18;
wire   [7:0] conv1_weight_address19;
reg    conv1_weight_ce19;
wire   [31:0] conv1_weight_q19;
wire   [7:0] conv1_weight_address20;
reg    conv1_weight_ce20;
wire   [31:0] conv1_weight_q20;
wire   [7:0] conv1_weight_address21;
reg    conv1_weight_ce21;
wire   [31:0] conv1_weight_q21;
wire   [7:0] conv1_weight_address22;
reg    conv1_weight_ce22;
wire   [31:0] conv1_weight_q22;
wire   [7:0] conv1_weight_address23;
reg    conv1_weight_ce23;
wire   [31:0] conv1_weight_q23;
wire   [7:0] conv1_weight_address24;
reg    conv1_weight_ce24;
wire   [31:0] conv1_weight_q24;
reg   [11:0] phi_mul186_load_reg_848;
wire    ap_CS_fsm_state2;
reg   [7:0] phi_mul_load_reg_854;
wire   [0:0] icmp_ln94_fu_541_p2;
reg   [31:0] B_reg_890;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [31:0] conv1_weight_load_reg_1020;
wire    ap_CS_fsm_state5;
reg   [31:0] conv1_weight_load_1_reg_1025;
reg   [31:0] conv1_weight_load_2_reg_1030;
reg   [31:0] conv1_weight_load_3_reg_1035;
reg   [31:0] conv1_weight_load_4_reg_1040;
reg   [31:0] conv1_weight_load_5_reg_1045;
reg   [31:0] conv1_weight_load_6_reg_1050;
reg   [31:0] conv1_weight_load_7_reg_1055;
reg   [31:0] conv1_weight_load_8_reg_1060;
reg   [31:0] conv1_weight_load_9_reg_1065;
reg   [31:0] conv1_weight_load_10_reg_1070;
reg   [31:0] conv1_weight_load_11_reg_1075;
reg   [31:0] conv1_weight_load_12_reg_1080;
reg   [31:0] conv1_weight_load_13_reg_1085;
reg   [31:0] conv1_weight_load_14_reg_1090;
reg   [31:0] conv1_weight_load_15_reg_1095;
reg   [31:0] conv1_weight_load_16_reg_1100;
reg   [31:0] conv1_weight_load_17_reg_1105;
reg   [31:0] conv1_weight_load_18_reg_1110;
reg   [31:0] conv1_weight_load_19_reg_1115;
reg   [31:0] conv1_weight_load_20_reg_1120;
reg   [31:0] conv1_weight_load_21_reg_1125;
reg   [31:0] conv1_weight_load_22_reg_1130;
reg   [31:0] conv1_weight_load_23_reg_1135;
reg   [31:0] conv1_weight_load_24_reg_1140;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_start;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_idle;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_ready;
wire   [12:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_out_data_address0;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_out_data_ce0;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_out_data_we0;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_out_data_d0;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_start;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_done;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_idle;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_ready;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWVALID;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWADDR;
wire   [0:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWID;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWLEN;
wire   [2:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWSIZE;
wire   [1:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWBURST;
wire   [1:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWLOCK;
wire   [3:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWCACHE;
wire   [2:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWPROT;
wire   [3:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWQOS;
wire   [3:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWREGION;
wire   [0:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWUSER;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_WVALID;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_WDATA;
wire   [3:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_WSTRB;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_WLAST;
wire   [0:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_WID;
wire   [0:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_WUSER;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARVALID;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARADDR;
wire   [0:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARID;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARLEN;
wire   [2:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARSIZE;
wire   [1:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARBURST;
wire   [1:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARLOCK;
wire   [3:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARCACHE;
wire   [2:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARPROT;
wire   [3:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARQOS;
wire   [3:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARREGION;
wire   [0:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARUSER;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_RREADY;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_BREADY;
wire   [12:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_out_data_address0;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_out_data_ce0;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_out_data_we0;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_out_data_d0;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1145_p_din0;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1145_p_din1;
wire   [1:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1145_p_opcode;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1145_p_ce;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1149_p_din0;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1149_p_din1;
wire   [1:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1149_p_opcode;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1149_p_ce;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1153_p_din0;
wire   [31:0] grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1153_p_din1;
wire    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1153_p_ce;
reg    grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_start_reg;
reg    grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_start_reg;
wire    ap_CS_fsm_state6;
wire   [31:0] zext_ln95_fu_553_p1;
wire   [31:0] zext_ln123_fu_573_p1;
wire   [31:0] zext_ln123_1_fu_586_p1;
wire   [31:0] zext_ln123_2_fu_597_p1;
wire   [31:0] zext_ln123_3_fu_607_p1;
wire   [31:0] zext_ln123_4_fu_617_p1;
wire   [31:0] zext_ln123_5_fu_627_p1;
wire   [31:0] zext_ln123_6_fu_637_p1;
wire   [31:0] zext_ln123_7_fu_647_p1;
wire   [31:0] zext_ln123_8_fu_657_p1;
wire   [31:0] zext_ln123_9_fu_667_p1;
wire   [31:0] zext_ln123_10_fu_677_p1;
wire   [31:0] zext_ln123_11_fu_687_p1;
wire   [31:0] zext_ln123_12_fu_697_p1;
wire   [31:0] zext_ln123_13_fu_707_p1;
wire   [31:0] zext_ln123_14_fu_717_p1;
wire   [31:0] zext_ln123_15_fu_727_p1;
wire   [31:0] zext_ln123_16_fu_737_p1;
wire   [31:0] zext_ln123_17_fu_747_p1;
wire   [31:0] zext_ln123_18_fu_757_p1;
wire   [31:0] zext_ln123_19_fu_767_p1;
wire   [31:0] zext_ln123_20_fu_777_p1;
wire   [31:0] zext_ln123_21_fu_787_p1;
wire   [31:0] zext_ln123_22_fu_797_p1;
wire   [31:0] zext_ln123_23_fu_807_p1;
wire   [31:0] zext_ln123_24_fu_817_p1;
reg   [11:0] phi_mul186_fu_104;
wire   [11:0] add_ln94_2_fu_529_p2;
reg   [7:0] phi_mul_fu_108;
wire   [7:0] add_ln94_3_fu_535_p2;
reg   [2:0] f_fu_112;
wire   [2:0] add_ln94_fu_547_p2;
wire   [6:0] trunc_ln123_fu_577_p1;
wire   [6:0] add_ln123_fu_580_p2;
wire   [6:0] add_ln123_1_fu_591_p2;
wire   [7:0] add_ln123_2_fu_602_p2;
wire   [7:0] add_ln123_3_fu_612_p2;
wire   [7:0] add_ln123_4_fu_622_p2;
wire   [7:0] add_ln123_5_fu_632_p2;
wire   [7:0] add_ln123_6_fu_642_p2;
wire   [7:0] add_ln123_7_fu_652_p2;
wire   [7:0] add_ln123_8_fu_662_p2;
wire   [7:0] add_ln123_9_fu_672_p2;
wire   [7:0] add_ln123_10_fu_682_p2;
wire   [7:0] add_ln123_11_fu_692_p2;
wire   [7:0] add_ln123_12_fu_702_p2;
wire   [7:0] add_ln123_13_fu_712_p2;
wire   [7:0] add_ln123_14_fu_722_p2;
wire   [7:0] add_ln123_15_fu_732_p2;
wire   [7:0] add_ln123_16_fu_742_p2;
wire   [7:0] add_ln123_17_fu_752_p2;
wire   [7:0] add_ln123_18_fu_762_p2;
wire   [7:0] add_ln123_19_fu_772_p2;
wire   [7:0] add_ln123_20_fu_782_p2;
wire   [7:0] add_ln123_21_fu_792_p2;
wire   [7:0] add_ln123_22_fu_802_p2;
wire   [7:0] add_ln123_23_fu_812_p2;
reg    grp_fu_1145_ce;
reg    grp_fu_1149_ce;
reg    grp_fu_1153_ce;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_start_reg = 1'b0;
#0 grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_start_reg = 1'b0;
end

lenet5_Convolution2d_float_s_conv1_bias_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
conv1_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_bias_address0),
    .ce0(conv1_bias_ce0),
    .q0(conv1_bias_q0)
);

lenet5_Convolution2d_float_s_conv1_weight_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
conv1_weight_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_weight_address0),
    .ce0(conv1_weight_ce0),
    .q0(conv1_weight_q0),
    .address1(conv1_weight_address1),
    .ce1(conv1_weight_ce1),
    .q1(conv1_weight_q1),
    .address2(conv1_weight_address2),
    .ce2(conv1_weight_ce2),
    .q2(conv1_weight_q2),
    .address3(conv1_weight_address3),
    .ce3(conv1_weight_ce3),
    .q3(conv1_weight_q3),
    .address4(conv1_weight_address4),
    .ce4(conv1_weight_ce4),
    .q4(conv1_weight_q4),
    .address5(conv1_weight_address5),
    .ce5(conv1_weight_ce5),
    .q5(conv1_weight_q5),
    .address6(conv1_weight_address6),
    .ce6(conv1_weight_ce6),
    .q6(conv1_weight_q6),
    .address7(conv1_weight_address7),
    .ce7(conv1_weight_ce7),
    .q7(conv1_weight_q7),
    .address8(conv1_weight_address8),
    .ce8(conv1_weight_ce8),
    .q8(conv1_weight_q8),
    .address9(conv1_weight_address9),
    .ce9(conv1_weight_ce9),
    .q9(conv1_weight_q9),
    .address10(conv1_weight_address10),
    .ce10(conv1_weight_ce10),
    .q10(conv1_weight_q10),
    .address11(conv1_weight_address11),
    .ce11(conv1_weight_ce11),
    .q11(conv1_weight_q11),
    .address12(conv1_weight_address12),
    .ce12(conv1_weight_ce12),
    .q12(conv1_weight_q12),
    .address13(conv1_weight_address13),
    .ce13(conv1_weight_ce13),
    .q13(conv1_weight_q13),
    .address14(conv1_weight_address14),
    .ce14(conv1_weight_ce14),
    .q14(conv1_weight_q14),
    .address15(conv1_weight_address15),
    .ce15(conv1_weight_ce15),
    .q15(conv1_weight_q15),
    .address16(conv1_weight_address16),
    .ce16(conv1_weight_ce16),
    .q16(conv1_weight_q16),
    .address17(conv1_weight_address17),
    .ce17(conv1_weight_ce17),
    .q17(conv1_weight_q17),
    .address18(conv1_weight_address18),
    .ce18(conv1_weight_ce18),
    .q18(conv1_weight_q18),
    .address19(conv1_weight_address19),
    .ce19(conv1_weight_ce19),
    .q19(conv1_weight_q19),
    .address20(conv1_weight_address20),
    .ce20(conv1_weight_ce20),
    .q20(conv1_weight_q20),
    .address21(conv1_weight_address21),
    .ce21(conv1_weight_ce21),
    .q21(conv1_weight_q21),
    .address22(conv1_weight_address22),
    .ce22(conv1_weight_ce22),
    .q22(conv1_weight_q22),
    .address23(conv1_weight_address23),
    .ce23(conv1_weight_ce23),
    .q23(conv1_weight_q23),
    .address24(conv1_weight_address24),
    .ce24(conv1_weight_ce24),
    .q24(conv1_weight_q24)
);

lenet5_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3 grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_start),
    .ap_done(grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done),
    .ap_idle(grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_idle),
    .ap_ready(grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_ready),
    .phi_mul186(phi_mul186_load_reg_848),
    .out_data_address0(grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_out_data_address0),
    .out_data_ce0(grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_out_data_ce0),
    .out_data_we0(grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_out_data_we0),
    .out_data_d0(grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_out_data_d0),
    .B(B_reg_890)
);

lenet5_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6 grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_start),
    .ap_done(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_done),
    .ap_idle(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_idle),
    .ap_ready(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_ready),
    .m_axi_data_AWVALID(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWVALID),
    .m_axi_data_AWREADY(1'b0),
    .m_axi_data_AWADDR(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWADDR),
    .m_axi_data_AWID(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWID),
    .m_axi_data_AWLEN(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWLEN),
    .m_axi_data_AWSIZE(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWSIZE),
    .m_axi_data_AWBURST(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWBURST),
    .m_axi_data_AWLOCK(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWLOCK),
    .m_axi_data_AWCACHE(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWCACHE),
    .m_axi_data_AWPROT(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWPROT),
    .m_axi_data_AWQOS(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWQOS),
    .m_axi_data_AWREGION(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWREGION),
    .m_axi_data_AWUSER(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_AWUSER),
    .m_axi_data_WVALID(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_WVALID),
    .m_axi_data_WREADY(1'b0),
    .m_axi_data_WDATA(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_WDATA),
    .m_axi_data_WSTRB(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_WSTRB),
    .m_axi_data_WLAST(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_WLAST),
    .m_axi_data_WID(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_WID),
    .m_axi_data_WUSER(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_WUSER),
    .m_axi_data_ARVALID(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARVALID),
    .m_axi_data_ARREADY(m_axi_data_ARREADY),
    .m_axi_data_ARADDR(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARADDR),
    .m_axi_data_ARID(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARID),
    .m_axi_data_ARLEN(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARLEN),
    .m_axi_data_ARSIZE(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARSIZE),
    .m_axi_data_ARBURST(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARBURST),
    .m_axi_data_ARLOCK(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARLOCK),
    .m_axi_data_ARCACHE(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARCACHE),
    .m_axi_data_ARPROT(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARPROT),
    .m_axi_data_ARQOS(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARQOS),
    .m_axi_data_ARREGION(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARREGION),
    .m_axi_data_ARUSER(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARUSER),
    .m_axi_data_RVALID(m_axi_data_RVALID),
    .m_axi_data_RREADY(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_RREADY),
    .m_axi_data_RDATA(m_axi_data_RDATA),
    .m_axi_data_RLAST(m_axi_data_RLAST),
    .m_axi_data_RID(m_axi_data_RID),
    .m_axi_data_RFIFONUM(m_axi_data_RFIFONUM),
    .m_axi_data_RUSER(m_axi_data_RUSER),
    .m_axi_data_RRESP(m_axi_data_RRESP),
    .m_axi_data_BVALID(1'b0),
    .m_axi_data_BREADY(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_BREADY),
    .m_axi_data_BRESP(2'd0),
    .m_axi_data_BID(1'd0),
    .m_axi_data_BUSER(1'd0),
    .in_data(in_data),
    .conv1_weight_load(conv1_weight_load_reg_1020),
    .conv1_weight_load_1(conv1_weight_load_1_reg_1025),
    .conv1_weight_load_2(conv1_weight_load_2_reg_1030),
    .conv1_weight_load_3(conv1_weight_load_3_reg_1035),
    .conv1_weight_load_4(conv1_weight_load_4_reg_1040),
    .conv1_weight_load_5(conv1_weight_load_5_reg_1045),
    .conv1_weight_load_6(conv1_weight_load_6_reg_1050),
    .conv1_weight_load_7(conv1_weight_load_7_reg_1055),
    .conv1_weight_load_8(conv1_weight_load_8_reg_1060),
    .conv1_weight_load_9(conv1_weight_load_9_reg_1065),
    .conv1_weight_load_10(conv1_weight_load_10_reg_1070),
    .conv1_weight_load_11(conv1_weight_load_11_reg_1075),
    .conv1_weight_load_12(conv1_weight_load_12_reg_1080),
    .conv1_weight_load_13(conv1_weight_load_13_reg_1085),
    .conv1_weight_load_14(conv1_weight_load_14_reg_1090),
    .conv1_weight_load_15(conv1_weight_load_15_reg_1095),
    .conv1_weight_load_16(conv1_weight_load_16_reg_1100),
    .conv1_weight_load_17(conv1_weight_load_17_reg_1105),
    .conv1_weight_load_18(conv1_weight_load_18_reg_1110),
    .conv1_weight_load_19(conv1_weight_load_19_reg_1115),
    .conv1_weight_load_20(conv1_weight_load_20_reg_1120),
    .conv1_weight_load_21(conv1_weight_load_21_reg_1125),
    .conv1_weight_load_22(conv1_weight_load_22_reg_1130),
    .conv1_weight_load_23(conv1_weight_load_23_reg_1135),
    .conv1_weight_load_24(conv1_weight_load_24_reg_1140),
    .phi_mul186(phi_mul186_load_reg_848),
    .out_data_address0(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_out_data_address0),
    .out_data_ce0(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_out_data_ce0),
    .out_data_we0(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_out_data_we0),
    .out_data_d0(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_out_data_d0),
    .out_data_q0(out_data_q0),
    .grp_fu_1145_p_din0(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1145_p_din0),
    .grp_fu_1145_p_din1(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1145_p_din1),
    .grp_fu_1145_p_opcode(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1145_p_opcode),
    .grp_fu_1145_p_dout0(grp_fu_236_p_dout0),
    .grp_fu_1145_p_ce(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1145_p_ce),
    .grp_fu_1149_p_din0(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1149_p_din0),
    .grp_fu_1149_p_din1(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1149_p_din1),
    .grp_fu_1149_p_opcode(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1149_p_opcode),
    .grp_fu_1149_p_dout0(grp_fu_240_p_dout0),
    .grp_fu_1149_p_ce(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1149_p_ce),
    .grp_fu_1153_p_din0(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1153_p_din0),
    .grp_fu_1153_p_din1(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1153_p_din1),
    .grp_fu_1153_p_dout0(grp_fu_244_p_dout0),
    .grp_fu_1153_p_ce(grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1153_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_start_reg <= 1'b1;
        end else if ((grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_ready == 1'b1)) begin
            grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_start_reg <= 1'b1;
        end else if ((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_ready == 1'b1)) begin
            grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        f_fu_112 <= 3'd0;
    end else if (((icmp_ln94_fu_541_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        f_fu_112 <= add_ln94_fu_547_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul186_fu_104 <= 12'd0;
    end else if (((icmp_ln94_fu_541_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        phi_mul186_fu_104 <= add_ln94_2_fu_529_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul_fu_108 <= 8'd0;
    end else if (((icmp_ln94_fu_541_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        phi_mul_fu_108 <= add_ln94_3_fu_535_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        B_reg_890 <= conv1_bias_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        conv1_weight_load_10_reg_1070 <= conv1_weight_q14;
        conv1_weight_load_11_reg_1075 <= conv1_weight_q13;
        conv1_weight_load_12_reg_1080 <= conv1_weight_q12;
        conv1_weight_load_13_reg_1085 <= conv1_weight_q11;
        conv1_weight_load_14_reg_1090 <= conv1_weight_q10;
        conv1_weight_load_15_reg_1095 <= conv1_weight_q9;
        conv1_weight_load_16_reg_1100 <= conv1_weight_q8;
        conv1_weight_load_17_reg_1105 <= conv1_weight_q7;
        conv1_weight_load_18_reg_1110 <= conv1_weight_q6;
        conv1_weight_load_19_reg_1115 <= conv1_weight_q5;
        conv1_weight_load_1_reg_1025 <= conv1_weight_q23;
        conv1_weight_load_20_reg_1120 <= conv1_weight_q4;
        conv1_weight_load_21_reg_1125 <= conv1_weight_q3;
        conv1_weight_load_22_reg_1130 <= conv1_weight_q2;
        conv1_weight_load_23_reg_1135 <= conv1_weight_q1;
        conv1_weight_load_24_reg_1140 <= conv1_weight_q0;
        conv1_weight_load_2_reg_1030 <= conv1_weight_q22;
        conv1_weight_load_3_reg_1035 <= conv1_weight_q21;
        conv1_weight_load_4_reg_1040 <= conv1_weight_q20;
        conv1_weight_load_5_reg_1045 <= conv1_weight_q19;
        conv1_weight_load_6_reg_1050 <= conv1_weight_q18;
        conv1_weight_load_7_reg_1055 <= conv1_weight_q17;
        conv1_weight_load_8_reg_1060 <= conv1_weight_q16;
        conv1_weight_load_9_reg_1065 <= conv1_weight_q15;
        conv1_weight_load_reg_1020 <= conv1_weight_q24;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        phi_mul186_load_reg_848 <= phi_mul186_fu_104;
        phi_mul_load_reg_854 <= phi_mul_fu_108;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln94_fu_541_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln94_fu_541_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        conv1_bias_ce0 = 1'b1;
    end else begin
        conv1_bias_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce0 = 1'b1;
    end else begin
        conv1_weight_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce1 = 1'b1;
    end else begin
        conv1_weight_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce10 = 1'b1;
    end else begin
        conv1_weight_ce10 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce11 = 1'b1;
    end else begin
        conv1_weight_ce11 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce12 = 1'b1;
    end else begin
        conv1_weight_ce12 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce13 = 1'b1;
    end else begin
        conv1_weight_ce13 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce14 = 1'b1;
    end else begin
        conv1_weight_ce14 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce15 = 1'b1;
    end else begin
        conv1_weight_ce15 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce16 = 1'b1;
    end else begin
        conv1_weight_ce16 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce17 = 1'b1;
    end else begin
        conv1_weight_ce17 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce18 = 1'b1;
    end else begin
        conv1_weight_ce18 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce19 = 1'b1;
    end else begin
        conv1_weight_ce19 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce2 = 1'b1;
    end else begin
        conv1_weight_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce20 = 1'b1;
    end else begin
        conv1_weight_ce20 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce21 = 1'b1;
    end else begin
        conv1_weight_ce21 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce22 = 1'b1;
    end else begin
        conv1_weight_ce22 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce23 = 1'b1;
    end else begin
        conv1_weight_ce23 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce24 = 1'b1;
    end else begin
        conv1_weight_ce24 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce3 = 1'b1;
    end else begin
        conv1_weight_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce4 = 1'b1;
    end else begin
        conv1_weight_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce5 = 1'b1;
    end else begin
        conv1_weight_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce6 = 1'b1;
    end else begin
        conv1_weight_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce7 = 1'b1;
    end else begin
        conv1_weight_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce8 = 1'b1;
    end else begin
        conv1_weight_ce8 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        conv1_weight_ce9 = 1'b1;
    end else begin
        conv1_weight_ce9 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_1145_ce = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1145_p_ce;
    end else begin
        grp_fu_1145_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_1149_ce = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1149_p_ce;
    end else begin
        grp_fu_1149_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_1153_ce = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1153_p_ce;
    end else begin
        grp_fu_1153_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        m_axi_data_ARVALID = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARVALID;
    end else begin
        m_axi_data_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        m_axi_data_RREADY = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_RREADY;
    end else begin
        m_axi_data_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_data_address0 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_out_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_address0 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_out_data_address0;
    end else begin
        out_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_data_ce0 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_out_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_ce0 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_out_data_ce0;
    end else begin
        out_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_data_d0 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_out_data_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_d0 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_out_data_d0;
    end else begin
        out_data_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_data_we0 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_out_data_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_we0 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_out_data_we0;
    end else begin
        out_data_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln94_fu_541_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln123_10_fu_682_p2 = (phi_mul_load_reg_854 + 8'd11);

assign add_ln123_11_fu_692_p2 = (phi_mul_load_reg_854 + 8'd12);

assign add_ln123_12_fu_702_p2 = (phi_mul_load_reg_854 + 8'd13);

assign add_ln123_13_fu_712_p2 = (phi_mul_load_reg_854 + 8'd14);

assign add_ln123_14_fu_722_p2 = (phi_mul_load_reg_854 + 8'd15);

assign add_ln123_15_fu_732_p2 = (phi_mul_load_reg_854 + 8'd16);

assign add_ln123_16_fu_742_p2 = (phi_mul_load_reg_854 + 8'd17);

assign add_ln123_17_fu_752_p2 = (phi_mul_load_reg_854 + 8'd18);

assign add_ln123_18_fu_762_p2 = (phi_mul_load_reg_854 + 8'd19);

assign add_ln123_19_fu_772_p2 = (phi_mul_load_reg_854 + 8'd20);

assign add_ln123_1_fu_591_p2 = (trunc_ln123_fu_577_p1 + 7'd2);

assign add_ln123_20_fu_782_p2 = (phi_mul_load_reg_854 + 8'd21);

assign add_ln123_21_fu_792_p2 = (phi_mul_load_reg_854 + 8'd22);

assign add_ln123_22_fu_802_p2 = (phi_mul_load_reg_854 + 8'd23);

assign add_ln123_23_fu_812_p2 = (phi_mul_load_reg_854 + 8'd24);

assign add_ln123_2_fu_602_p2 = (phi_mul_load_reg_854 + 8'd3);

assign add_ln123_3_fu_612_p2 = (phi_mul_load_reg_854 + 8'd4);

assign add_ln123_4_fu_622_p2 = (phi_mul_load_reg_854 + 8'd5);

assign add_ln123_5_fu_632_p2 = (phi_mul_load_reg_854 + 8'd6);

assign add_ln123_6_fu_642_p2 = (phi_mul_load_reg_854 + 8'd7);

assign add_ln123_7_fu_652_p2 = (phi_mul_load_reg_854 + 8'd8);

assign add_ln123_8_fu_662_p2 = (phi_mul_load_reg_854 + 8'd9);

assign add_ln123_9_fu_672_p2 = (phi_mul_load_reg_854 + 8'd10);

assign add_ln123_fu_580_p2 = (trunc_ln123_fu_577_p1 + 7'd1);

assign add_ln94_2_fu_529_p2 = (phi_mul186_fu_104 + 12'd784);

assign add_ln94_3_fu_535_p2 = (phi_mul_fu_108 + 8'd25);

assign add_ln94_fu_547_p2 = (f_fu_112 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign conv1_bias_address0 = zext_ln95_fu_553_p1;

assign conv1_weight_address0 = zext_ln123_24_fu_817_p1;

assign conv1_weight_address1 = zext_ln123_23_fu_807_p1;

assign conv1_weight_address10 = zext_ln123_14_fu_717_p1;

assign conv1_weight_address11 = zext_ln123_13_fu_707_p1;

assign conv1_weight_address12 = zext_ln123_12_fu_697_p1;

assign conv1_weight_address13 = zext_ln123_11_fu_687_p1;

assign conv1_weight_address14 = zext_ln123_10_fu_677_p1;

assign conv1_weight_address15 = zext_ln123_9_fu_667_p1;

assign conv1_weight_address16 = zext_ln123_8_fu_657_p1;

assign conv1_weight_address17 = zext_ln123_7_fu_647_p1;

assign conv1_weight_address18 = zext_ln123_6_fu_637_p1;

assign conv1_weight_address19 = zext_ln123_5_fu_627_p1;

assign conv1_weight_address2 = zext_ln123_22_fu_797_p1;

assign conv1_weight_address20 = zext_ln123_4_fu_617_p1;

assign conv1_weight_address21 = zext_ln123_3_fu_607_p1;

assign conv1_weight_address22 = zext_ln123_2_fu_597_p1;

assign conv1_weight_address23 = zext_ln123_1_fu_586_p1;

assign conv1_weight_address24 = zext_ln123_fu_573_p1;

assign conv1_weight_address3 = zext_ln123_21_fu_787_p1;

assign conv1_weight_address4 = zext_ln123_20_fu_777_p1;

assign conv1_weight_address5 = zext_ln123_19_fu_767_p1;

assign conv1_weight_address6 = zext_ln123_18_fu_757_p1;

assign conv1_weight_address7 = zext_ln123_17_fu_747_p1;

assign conv1_weight_address8 = zext_ln123_16_fu_737_p1;

assign conv1_weight_address9 = zext_ln123_15_fu_727_p1;

assign grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_start = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_ap_start_reg;

assign grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_start = grp_Convolution2d_float_Pipeline_VITIS_LOOP_97_2_VITIS_LOOP_98_3_fu_436_ap_start_reg;

assign grp_fu_236_p_ce = grp_fu_1145_ce;

assign grp_fu_236_p_din0 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1145_p_din0;

assign grp_fu_236_p_din1 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1145_p_din1;

assign grp_fu_236_p_opcode = 2'd0;

assign grp_fu_240_p_ce = grp_fu_1149_ce;

assign grp_fu_240_p_din0 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1149_p_din0;

assign grp_fu_240_p_din1 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1149_p_din1;

assign grp_fu_240_p_opcode = 2'd0;

assign grp_fu_244_p_ce = grp_fu_1153_ce;

assign grp_fu_244_p_din0 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1153_p_din0;

assign grp_fu_244_p_din1 = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_grp_fu_1153_p_din1;

assign icmp_ln94_fu_541_p2 = ((f_fu_112 == 3'd6) ? 1'b1 : 1'b0);

assign m_axi_data_ARADDR = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARADDR;

assign m_axi_data_ARBURST = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARBURST;

assign m_axi_data_ARCACHE = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARCACHE;

assign m_axi_data_ARID = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARID;

assign m_axi_data_ARLEN = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARLEN;

assign m_axi_data_ARLOCK = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARLOCK;

assign m_axi_data_ARPROT = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARPROT;

assign m_axi_data_ARQOS = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARQOS;

assign m_axi_data_ARREGION = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARREGION;

assign m_axi_data_ARSIZE = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARSIZE;

assign m_axi_data_ARUSER = grp_Convolution2d_float_Pipeline_VITIS_LOOP_111_5_VITIS_LOOP_112_6_fu_445_m_axi_data_ARUSER;

assign m_axi_data_AWADDR = 32'd0;

assign m_axi_data_AWBURST = 2'd0;

assign m_axi_data_AWCACHE = 4'd0;

assign m_axi_data_AWID = 1'd0;

assign m_axi_data_AWLEN = 32'd0;

assign m_axi_data_AWLOCK = 2'd0;

assign m_axi_data_AWPROT = 3'd0;

assign m_axi_data_AWQOS = 4'd0;

assign m_axi_data_AWREGION = 4'd0;

assign m_axi_data_AWSIZE = 3'd0;

assign m_axi_data_AWUSER = 1'd0;

assign m_axi_data_AWVALID = 1'b0;

assign m_axi_data_BREADY = 1'b0;

assign m_axi_data_WDATA = 32'd0;

assign m_axi_data_WID = 1'd0;

assign m_axi_data_WLAST = 1'b0;

assign m_axi_data_WSTRB = 4'd0;

assign m_axi_data_WUSER = 1'd0;

assign m_axi_data_WVALID = 1'b0;

assign trunc_ln123_fu_577_p1 = phi_mul_load_reg_854[6:0];

assign zext_ln123_10_fu_677_p1 = add_ln123_9_fu_672_p2;

assign zext_ln123_11_fu_687_p1 = add_ln123_10_fu_682_p2;

assign zext_ln123_12_fu_697_p1 = add_ln123_11_fu_692_p2;

assign zext_ln123_13_fu_707_p1 = add_ln123_12_fu_702_p2;

assign zext_ln123_14_fu_717_p1 = add_ln123_13_fu_712_p2;

assign zext_ln123_15_fu_727_p1 = add_ln123_14_fu_722_p2;

assign zext_ln123_16_fu_737_p1 = add_ln123_15_fu_732_p2;

assign zext_ln123_17_fu_747_p1 = add_ln123_16_fu_742_p2;

assign zext_ln123_18_fu_757_p1 = add_ln123_17_fu_752_p2;

assign zext_ln123_19_fu_767_p1 = add_ln123_18_fu_762_p2;

assign zext_ln123_1_fu_586_p1 = add_ln123_fu_580_p2;

assign zext_ln123_20_fu_777_p1 = add_ln123_19_fu_772_p2;

assign zext_ln123_21_fu_787_p1 = add_ln123_20_fu_782_p2;

assign zext_ln123_22_fu_797_p1 = add_ln123_21_fu_792_p2;

assign zext_ln123_23_fu_807_p1 = add_ln123_22_fu_802_p2;

assign zext_ln123_24_fu_817_p1 = add_ln123_23_fu_812_p2;

assign zext_ln123_2_fu_597_p1 = add_ln123_1_fu_591_p2;

assign zext_ln123_3_fu_607_p1 = add_ln123_2_fu_602_p2;

assign zext_ln123_4_fu_617_p1 = add_ln123_3_fu_612_p2;

assign zext_ln123_5_fu_627_p1 = add_ln123_4_fu_622_p2;

assign zext_ln123_6_fu_637_p1 = add_ln123_5_fu_632_p2;

assign zext_ln123_7_fu_647_p1 = add_ln123_6_fu_642_p2;

assign zext_ln123_8_fu_657_p1 = add_ln123_7_fu_652_p2;

assign zext_ln123_9_fu_667_p1 = add_ln123_8_fu_662_p2;

assign zext_ln123_fu_573_p1 = phi_mul_load_reg_854;

assign zext_ln95_fu_553_p1 = f_fu_112;

endmodule //lenet5_Convolution2d_float_s
