// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lenet5_lenet5_Pipeline_VITIS_LOOP_64_1_VITIS_LOOP_68_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p2_out_data_address0,
        p2_out_data_ce0,
        p2_out_data_q0,
        f1_out_data_address0,
        f1_out_data_ce0,
        f1_out_data_we0,
        f1_out_data_d0,
        grp_fu_236_p_din0,
        grp_fu_236_p_din1,
        grp_fu_236_p_opcode,
        grp_fu_236_p_dout0,
        grp_fu_236_p_ce,
        grp_fu_244_p_din0,
        grp_fu_244_p_din1,
        grp_fu_244_p_dout0,
        grp_fu_244_p_ce,
        grp_fu_248_p_din0,
        grp_fu_248_p_din1,
        grp_fu_248_p_opcode,
        grp_fu_248_p_dout0,
        grp_fu_248_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 6'd1;
parameter    ap_ST_fsm_pp0_stage1 = 6'd2;
parameter    ap_ST_fsm_pp0_stage2 = 6'd4;
parameter    ap_ST_fsm_pp0_stage3 = 6'd8;
parameter    ap_ST_fsm_pp0_stage4 = 6'd16;
parameter    ap_ST_fsm_pp0_stage5 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] p2_out_data_address0;
output   p2_out_data_ce0;
input  [31:0] p2_out_data_q0;
output  [6:0] f1_out_data_address0;
output   f1_out_data_ce0;
output   f1_out_data_we0;
output  [31:0] f1_out_data_d0;
output  [31:0] grp_fu_236_p_din0;
output  [31:0] grp_fu_236_p_din1;
output  [1:0] grp_fu_236_p_opcode;
input  [31:0] grp_fu_236_p_dout0;
output   grp_fu_236_p_ce;
output  [31:0] grp_fu_244_p_din0;
output  [31:0] grp_fu_244_p_din1;
input  [31:0] grp_fu_244_p_dout0;
output   grp_fu_244_p_ce;
output  [31:0] grp_fu_248_p_din0;
output  [31:0] grp_fu_248_p_din1;
output  [4:0] grp_fu_248_p_opcode;
input  [0:0] grp_fu_248_p_dout0;
output   grp_fu_248_p_ce;

reg ap_idle;
reg p2_out_data_ce0;
reg f1_out_data_ce0;
reg f1_out_data_we0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_state12_pp0_stage5_iter1;
wire    ap_block_state18_pp0_stage5_iter2;
wire    ap_block_pp0_stage5_subdone;
reg   [0:0] icmp_ln64_reg_354;
reg    ap_condition_exit_pp0_iter0_stage5;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] fc1_bias_address0;
reg    fc1_bias_ce0;
wire   [31:0] fc1_bias_q0;
wire   [15:0] fc1_weight_address0;
reg    fc1_weight_ce0;
wire   [31:0] fc1_weight_q0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state7_pp0_stage0_iter1;
wire    ap_block_state13_pp0_stage0_iter2;
wire    ap_block_state19_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln64_fu_162_p2;
reg   [0:0] icmp_ln64_reg_354_pp0_iter1_reg;
reg   [0:0] icmp_ln64_reg_354_pp0_iter2_reg;
wire   [0:0] icmp_ln68_fu_186_p2;
reg   [0:0] icmp_ln68_reg_358;
reg   [0:0] icmp_ln68_reg_358_pp0_iter1_reg;
wire   [8:0] select_ln64_1_fu_192_p3;
reg   [8:0] select_ln64_1_reg_363;
wire   [6:0] select_ln64_3_fu_200_p3;
reg   [6:0] select_ln64_3_reg_368;
reg   [6:0] select_ln64_3_reg_368_pp0_iter1_reg;
wire   [0:0] ifzero_fu_223_p2;
reg   [0:0] ifzero_reg_383;
reg   [0:0] ifzero_reg_383_pp0_iter1_reg;
reg   [0:0] ifzero_reg_383_pp0_iter2_reg;
reg   [0:0] ifzero_reg_383_pp0_iter3_reg;
reg   [31:0] pX_load_reg_387;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state8_pp0_stage1_iter1;
wire    ap_block_state14_pp0_stage1_iter2;
wire    ap_block_state20_pp0_stage1_iter3;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state9_pp0_stage2_iter1;
wire    ap_block_state15_pp0_stage2_iter2;
wire    ap_block_state21_pp0_stage2_iter3;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state10_pp0_stage3_iter1;
wire    ap_block_state16_pp0_stage3_iter2;
wire    ap_block_state22_pp0_stage3_iter3;
wire    ap_block_pp0_stage3_11001;
reg   [31:0] pW_load_reg_402;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state11_pp0_stage4_iter1;
wire    ap_block_state17_pp0_stage4_iter2;
wire    ap_block_pp0_stage4_11001;
wire   [31:0] select_ln64_fu_254_p3;
reg   [31:0] select_ln64_reg_407;
reg   [31:0] mul20_i_reg_412;
wire   [31:0] zext_ln64_fu_261_p1;
reg   [31:0] zext_ln64_reg_417;
reg   [31:0] zext_ln64_reg_417_pp0_iter3_reg;
reg   [31:0] fc1_bias_load_reg_427;
reg   [31:0] sum_1_reg_432;
reg   [31:0] add22_i_reg_438;
wire   [31:0] select_ln74_fu_310_p3;
reg   [31:0] select_ln74_reg_445;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage3_subdone;
wire   [31:0] zext_ln68_fu_212_p1;
wire    ap_block_pp0_stage0;
wire   [31:0] zext_ln70_fu_247_p1;
wire    ap_block_pp0_stage3;
reg   [8:0] i_fu_58;
wire   [8:0] i_2_fu_217_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_i_load;
reg   [31:0] sum_fu_62;
reg   [31:0] ap_sig_allocacmp_sum_load;
wire    ap_block_pp0_stage2;
reg   [6:0] o_fu_66;
reg   [6:0] ap_sig_allocacmp_o_load;
reg   [15:0] indvar_flatten_fu_70;
wire   [15:0] add_ln64_fu_168_p2;
reg   [15:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [31:0] grp_fu_126_p0;
reg   [31:0] grp_fu_126_p1;
wire    ap_block_pp0_stage5;
wire    ap_block_pp0_stage1;
wire   [6:0] o_2_fu_180_p2;
wire   [15:0] grp_fu_317_p3;
wire   [31:0] bitcast_ln74_fu_269_p1;
wire   [7:0] tmp_fu_272_p4;
wire   [22:0] trunc_ln74_fu_282_p1;
wire   [0:0] icmp_ln74_1_fu_292_p2;
wire   [0:0] icmp_ln74_fu_286_p2;
wire   [0:0] or_ln74_fu_298_p2;
wire   [0:0] and_ln74_fu_304_p2;
wire   [6:0] grp_fu_317_p0;
wire   [8:0] grp_fu_317_p1;
wire   [8:0] grp_fu_317_p2;
wire    ap_block_pp0_stage1_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
wire    ap_block_pp0_stage5_11001;
reg    ap_condition_exit_pp0_iter2_stage3;
reg    ap_idle_pp0_0to1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [5:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to3;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage3_00001;
wire    ap_block_pp0_stage2_00001;
wire   [15:0] grp_fu_317_p00;
wire   [15:0] grp_fu_317_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

lenet5_lenet5_Pipeline_VITIS_LOOP_64_1_VITIS_LOOP_68_2_fc1_bias_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
fc1_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc1_bias_address0),
    .ce0(fc1_bias_ce0),
    .q0(fc1_bias_q0)
);

lenet5_lenet5_Pipeline_VITIS_LOOP_64_1_VITIS_LOOP_68_2_fc1_weight_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 48000 ),
    .AddressWidth( 16 ))
fc1_weight_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc1_weight_address0),
    .ce0(fc1_weight_ce0),
    .q0(fc1_weight_q0)
);

lenet5_mac_muladd_7ns_9ns_9ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mac_muladd_7ns_9ns_9ns_16_4_1_U111(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_317_p0),
    .din1(grp_fu_317_p1),
    .din2(grp_fu_317_p2),
    .ce(1'b1),
    .dout(grp_fu_317_p3)
);

lenet5_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage5),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage5)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln64_fu_162_p2 == 1'd0))) begin
            i_fu_58 <= i_2_fu_217_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_58 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln64_fu_162_p2 == 1'd0))) begin
            indvar_flatten_fu_70 <= add_ln64_fu_168_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_70 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln64_fu_162_p2 == 1'd0))) begin
            o_fu_66 <= select_ln64_3_fu_200_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            o_fu_66 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_fu_62 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sum_fu_62 <= sum_1_reg_432;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ifzero_reg_383_pp0_iter2_reg == 1'd1))) begin
        add22_i_reg_438 <= grp_fu_236_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fc1_bias_load_reg_427 <= fc1_bias_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln64_reg_354 <= icmp_ln64_fu_162_p2;
        icmp_ln64_reg_354_pp0_iter1_reg <= icmp_ln64_reg_354;
        icmp_ln64_reg_354_pp0_iter2_reg <= icmp_ln64_reg_354_pp0_iter1_reg;
        icmp_ln68_reg_358_pp0_iter1_reg <= icmp_ln68_reg_358;
        ifzero_reg_383_pp0_iter1_reg <= ifzero_reg_383;
        ifzero_reg_383_pp0_iter2_reg <= ifzero_reg_383_pp0_iter1_reg;
        ifzero_reg_383_pp0_iter3_reg <= ifzero_reg_383_pp0_iter2_reg;
        select_ln64_3_reg_368_pp0_iter1_reg <= select_ln64_3_reg_368;
        zext_ln64_reg_417[6 : 0] <= zext_ln64_fu_261_p1[6 : 0];
        zext_ln64_reg_417_pp0_iter3_reg[6 : 0] <= zext_ln64_reg_417[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln64_fu_162_p2 == 1'd0))) begin
        icmp_ln68_reg_358 <= icmp_ln68_fu_186_p2;
        ifzero_reg_383 <= ifzero_fu_223_p2;
        select_ln64_1_reg_363 <= select_ln64_1_fu_192_p3;
        select_ln64_3_reg_368 <= select_ln64_3_fu_200_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul20_i_reg_412 <= grp_fu_244_p_dout0;
        select_ln64_reg_407 <= select_ln64_fu_254_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_354 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        pW_load_reg_402 <= fc1_weight_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_354 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pX_load_reg_387 <= p2_out_data_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ifzero_reg_383_pp0_iter3_reg == 1'd1))) begin
        select_ln74_reg_445 <= select_ln74_fu_310_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sum_1_reg_432 <= grp_fu_236_p_dout0;
    end
end

always @ (*) begin
    if (((icmp_ln64_reg_354 == 1'd1) & (1'b0 == ap_block_pp0_stage5_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_condition_exit_pp0_iter0_stage5 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln64_reg_354_pp0_iter2_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 9'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 16'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_o_load = 7'd0;
    end else begin
        ap_sig_allocacmp_o_load = o_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_sum_load = sum_1_reg_432;
    end else begin
        ap_sig_allocacmp_sum_load = sum_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        f1_out_data_ce0 = 1'b1;
    end else begin
        f1_out_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ifzero_reg_383_pp0_iter3_reg == 1'd1))) begin
        f1_out_data_we0 = 1'b1;
    end else begin
        f1_out_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fc1_bias_ce0 = 1'b1;
    end else begin
        fc1_bias_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        fc1_weight_ce0 = 1'b1;
    end else begin
        fc1_weight_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_126_p0 = sum_1_reg_432;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_126_p0 = select_ln64_reg_407;
    end else begin
        grp_fu_126_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_126_p1 = fc1_bias_load_reg_427;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_126_p1 = mul20_i_reg_412;
    end else begin
        grp_fu_126_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p2_out_data_ce0 = 1'b1;
    end else begin
        p2_out_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage3))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln64_fu_168_p2 = (ap_sig_allocacmp_indvar_flatten_load + 16'd1);

assign and_ln74_fu_304_p2 = (or_ln74_fu_298_p2 & grp_fu_248_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage5_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage5;

assign bitcast_ln74_fu_269_p1 = add22_i_reg_438;

assign f1_out_data_address0 = zext_ln64_reg_417_pp0_iter3_reg;

assign f1_out_data_d0 = select_ln74_reg_445;

assign fc1_bias_address0 = zext_ln64_fu_261_p1;

assign fc1_weight_address0 = zext_ln70_fu_247_p1;

assign grp_fu_236_p_ce = 1'b1;

assign grp_fu_236_p_din0 = grp_fu_126_p0;

assign grp_fu_236_p_din1 = grp_fu_126_p1;

assign grp_fu_236_p_opcode = 2'd0;

assign grp_fu_244_p_ce = 1'b1;

assign grp_fu_244_p_din0 = pX_load_reg_387;

assign grp_fu_244_p_din1 = pW_load_reg_402;

assign grp_fu_248_p_ce = 1'b1;

assign grp_fu_248_p_din0 = add22_i_reg_438;

assign grp_fu_248_p_din1 = 32'd0;

assign grp_fu_248_p_opcode = 5'd5;

assign grp_fu_317_p0 = grp_fu_317_p00;

assign grp_fu_317_p00 = select_ln64_3_fu_200_p3;

assign grp_fu_317_p1 = 16'd400;

assign grp_fu_317_p2 = grp_fu_317_p20;

assign grp_fu_317_p20 = select_ln64_1_reg_363;

assign i_2_fu_217_p2 = (select_ln64_1_fu_192_p3 + 9'd1);

assign icmp_ln64_fu_162_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 16'd48000) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_186_p2 = ((ap_sig_allocacmp_i_load == 9'd400) ? 1'b1 : 1'b0);

assign icmp_ln74_1_fu_292_p2 = ((trunc_ln74_fu_282_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_286_p2 = ((tmp_fu_272_p4 != 8'd255) ? 1'b1 : 1'b0);

assign ifzero_fu_223_p2 = ((i_2_fu_217_p2 == 9'd400) ? 1'b1 : 1'b0);

assign o_2_fu_180_p2 = (ap_sig_allocacmp_o_load + 7'd1);

assign or_ln74_fu_298_p2 = (icmp_ln74_fu_286_p2 | icmp_ln74_1_fu_292_p2);

assign p2_out_data_address0 = zext_ln68_fu_212_p1;

assign select_ln64_1_fu_192_p3 = ((icmp_ln68_fu_186_p2[0:0] == 1'b1) ? 9'd0 : ap_sig_allocacmp_i_load);

assign select_ln64_3_fu_200_p3 = ((icmp_ln68_fu_186_p2[0:0] == 1'b1) ? o_2_fu_180_p2 : ap_sig_allocacmp_o_load);

assign select_ln64_fu_254_p3 = ((icmp_ln68_reg_358_pp0_iter1_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_sum_load);

assign select_ln74_fu_310_p3 = ((and_ln74_fu_304_p2[0:0] == 1'b1) ? 32'd0 : add22_i_reg_438);

assign tmp_fu_272_p4 = {{bitcast_ln74_fu_269_p1[30:23]}};

assign trunc_ln74_fu_282_p1 = bitcast_ln74_fu_269_p1[22:0];

assign zext_ln64_fu_261_p1 = select_ln64_3_reg_368_pp0_iter1_reg;

assign zext_ln68_fu_212_p1 = select_ln64_1_fu_192_p3;

assign zext_ln70_fu_247_p1 = grp_fu_317_p3;

always @ (posedge ap_clk) begin
    zext_ln64_reg_417[31:7] <= 25'b0000000000000000000000000;
    zext_ln64_reg_417_pp0_iter3_reg[31:7] <= 25'b0000000000000000000000000;
end

endmodule //lenet5_lenet5_Pipeline_VITIS_LOOP_64_1_VITIS_LOOP_68_2
